# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/90a5dd7a-20df-4dfe-a723-ebd5eda4b11e";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/202a0c1b-adc1-4226-81b5-40c192b1a341";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/90a5dd7a-20df-4dfe-a723-ebd5eda4b11e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/90a5dd7a-20df-4dfe-a723-ebd5eda4b11e";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home/rico/rstore" =
    { device = "/dev/disk/by-uuid/90a5dd7a-20df-4dfe-a723-ebd5eda4b11e";
      fsType = "btrfs";
      options = [ "subvol=@rstore" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EA5C-8B75";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
